
<body>
<div class="wrapper">
    <div id="myModal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <span class="close">&times;</span>
                <h2>Hello Player!</h2>
            </div>
            <hr>
            <div class="modal-body">
                <p>You have stumbled upon my humble game.</p>
                <p>Care to play?</p>
            </div>
            <hr>
            <div class="modal-footer">
                <h3>Modal Footer</h3>
            </div>
            <hr>
            <p>Press the button to start, hope you like it :)</p>
            <hr>
            <button id="start">Game On!</button>
        </div>
    </div>
    <div class="startText-Wrapper">
        <h2 class="startText-Content">< Press Space To Start ></h2>
    </div>
    <canvas id="c">
    </canvas>
</body>

