
<body>
<h1>Hello Player!</h1>
<ol>
    <li>
        <a href="dashboard/logout">Logout</a>
    </li>
    <li>
        <a href="dashboard/delete">KILL ME</a>
    </li>
    <li>
        <a href="dashboard/info">Info</a>
    </li>
</ol>
<form id="AJAXInsert" action="dashboard/Insert" method="post">
    <input type="text" title="name" name="text">
    <input type="submit">
</form>
<div id="info"></div>
</body>